// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/human": {
            "get": {
                "description": "Получить всех людей",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "люди"
                ],
                "summary": "Получить всех людей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Возраст от",
                        "name": "age_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Возраст до",
                        "name": "age_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Пол",
                        "name": "gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Национальность",
                        "name": "nationaly",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Максимальное количество возвращаемых машин",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Число первых пропущенных возвращаемых машин",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_P1xart_effective_mobile_service_internal_controller_v1_response.GetAllHumans"
                        }
                    }
                }
            }
        },
        "/v1/human/": {
            "post": {
                "description": "Создание нового человека",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "люди"
                ],
                "summary": "Создание нового человека",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_P1xart_effective_mobile_service_internal_controller_v1_request.CreateHuman"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_P1xart_effective_mobile_service_internal_controller_v1_request.CreateHuman": {
            "type": "object",
            "required": [
                "name",
                "surname"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Vasiliy"
                },
                "potronymic": {
                    "type": "string",
                    "example": "Vasilevich"
                },
                "surname": {
                    "type": "string",
                    "example": "Vasiliev"
                }
            }
        },
        "github_com_P1xart_effective_mobile_service_internal_controller_v1_response.GetAllHumans": {
            "type": "object",
            "properties": {
                "humans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_P1xart_effective_mobile_service_internal_entity.Human"
                    }
                }
            }
        },
        "github_com_P1xart_effective_mobile_service_internal_entity.Human": {
            "type": "object",
            "properties": {
                "Gender": {
                    "type": "string"
                },
                "age": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nationaly": {
                    "type": "string"
                },
                "potronymic": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "CRM Backend API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
