definitions:
  github_com_P1xart_effective_mobile_service_internal_controller_v1_request.CreateHuman:
    properties:
      name:
        example: Vasiliy
        type: string
      potronymic:
        example: Vasilevich
        type: string
      surname:
        example: Vasiliev
        type: string
    required:
    - name
    - surname
    type: object
  github_com_P1xart_effective_mobile_service_internal_controller_v1_request.UpdateHuman:
    properties:
      age:
        example: 22
        type: integer
      gender:
        example: male
        type: string
      name:
        example: Igor
        type: string
      nationality:
        example: US
        type: string
      potronymic:
        example: Igorevich
        type: string
      surname:
        example: Igorev
        type: string
    type: object
  github_com_P1xart_effective_mobile_service_internal_controller_v1_response.GetAllHumans:
    properties:
      humans:
        items:
          $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_entity.Human'
        type: array
    type: object
  github_com_P1xart_effective_mobile_service_internal_entity.Human:
    properties:
      Gender:
        type: string
      age:
        type: integer
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      potronymic:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
  title: Тестовое
  version: "1.0"
paths:
  /v1/human:
    get:
      consumes:
      - application/json
      description: Получить всех людей
      parameters:
      - description: Возраст от
        in: query
        name: age_from
        type: string
      - description: Возраст до
        in: query
        name: age_to
        type: string
      - description: Пол
        in: query
        name: gender
        type: string
      - description: Национальность
        in: query
        name: nationaly
        type: string
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_controller_v1_response.GetAllHumans'
      summary: Получить всех людей
      tags:
      - люди
  /v1/human/:
    post:
      consumes:
      - application/json
      description: Создание нового человека
      parameters:
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_controller_v1_request.CreateHuman'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_entity.Human'
      summary: Создание нового человека
      tags:
      - люди
  /v1/human/{id}:
    delete:
      description: Удалить человека по его идентификатору
      parameters:
      - description: Идентификатор человека
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: Удалить человека по его идентификатору
      tags:
      - люди
    patch:
      consumes:
      - application/json
      description: Обновить человека по его идентификатору. Принимает JSON с обновленными
        полями
      parameters:
      - description: Идентификатор человека
        in: path
        name: id
        required: true
        type: string
      - description: Тело запроса
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_controller_v1_request.UpdateHuman'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_P1xart_effective_mobile_service_internal_entity.Human'
      summary: Обновить человека по его идентификатору
      tags:
      - люди
swagger: "2.0"
